apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: example-container
      image: nginx:latest
      volumeMounts:
        - name: example-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: example-volume
      persistentVolumeClaim:
        claimName: example-pvc
