apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: example-1-three-container
  name: example-1-three-container
spec:
  containers:
  - image: nginx
    name: example-1-nginx
  - image: redis
    name: example-1-redis
  - image: ubuntu
    name: example-1-ubuntu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
